# Basics of PyTorch


It is an open source deep learning library. Torch was a very powerful scientific computing library but was implemented in Lua programming language.

Meta AI engineer introduced PyTorch by implement torch in python.

Features :  

1. High performance tensor-based operations, especially on GPU.
2. It is compatible with python and other libraries like pandas, numpy etc.
3. Dynamic computation graph : we can have computation graph at runtime. It helps in faster debugging and experimentation becomes easier.

Computation graph : a directed acyclic graph which represent the order in which the computation are happening.

It is very popular in research environments but it is still behind keras tensorflow in production environments.

1. Torchscript for model searization and optimization. Once searlized a model can be used in environment like andriod which does not have python or pytorch

2. Improved performance with Caffe2 integration . Caffe2 was also a library for scalable (high model and data). So they merged them.

3. Supprot for distributed training

4. ONNX support. It is an open source format for neural networks. This allows interoperatablity between libraries.

5. Quanitzation for model compression and efficiency. To reduce the size of the model, by using lower precision.

6. torchvision , torchtext, torchaudio. They provide domain specific datasets, fucntions, pretrained model.

In [6]:
# Tensors are multidimensional arrays : they are storage and computation efficient. Also they can represent any real world info used in deep learning (images, videos, audio, text using word embedding), also tensor are GPU efficient.
import torch
# dim 0
zero_dim_scalar = torch.tensor(5)
print(zero_dim_scalar)
# dim 1
one_dim_vector = torch.tensor([1,2,3])
print(one_dim_vector) # usage : word embedding for a word
# dim 2
two_dim_matrix = torch.tensor([[1,2,3],[4,5,6]])
print(two_dim_matrix) # usage : image representation (grayscale)

tensor(5)
tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
# some specs of GOOGLE COLAB
print(torch.__version__)

# CUDA : Compute Unified Device Architecture
if torch.cuda.is_available():
  print("GPU is available")
  print(torch.cuda.get_device_name(0))
else:
  print("GPU is not available")

2.5.1+cu121
GPU is not available


In [8]:
print(torch.cuda.get_device_name(0)) # always use this statement when you are sure that there is some device available or when inside some if else.

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

# Creating Tensors

In [10]:
a = torch.empty(2,3)
print(a) # doesn't initializes
b = torch.zeros(2,3)
print(b) # initialize everything to 0
c = torch.ones(2,3,4)
print(c) # initialize everything to 1

tensor([[4.8408e+30, 1.1693e-19, 1.3563e-19],
        [1.5637e-01, 1.2696e+31, 1.8062e+28]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [11]:
print(type(a))
print(a.dtype)

<class 'torch.Tensor'>
torch.float32


In [16]:
d = torch.rand(2,3)
print(d) # can also specify seed to maintain reproducibility

tensor([[0.6022, 0.5339, 0.2912],
        [0.3172, 0.2877, 0.9346]])


In [18]:
e = torch.randint(low = 0, high = 100 , size =  (10, 3) , dtype = torch.float64) # low , high , number of elements
print(e)

tensor([[ 0., 31.,  5.],
        [20., 42., 61.],
        [16., 57., 23.],
        [69., 56., 51.],
        [20., 58., 45.],
        [10., 65.,  9.],
        [ 1., 44., 97.],
        [35., 88., 18.],
        [83., 60., 38.],
        [22., 17., 37.]], dtype=torch.float64)


In [19]:
f = torch.tensor([[1,2,3], [4,5,6]])
print(f)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [22]:
g = torch.linspace(start = 0.1, end = 1, steps = 10)
print(g)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [23]:
h = torch.eye(5) # identity matrix
print(h)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [32]:
i = torch.full((2,3), 5)
print(i) # all values 5

tensor([[5, 5, 5],
        [5, 5, 5]])


In [33]:
i.shape

torch.Size([2, 3])

In [34]:
g.shape

torch.Size([10])

In [35]:
torch.empty_like(g) # create a new tensor with the size same as  g . Like function can be used for such tasks.

tensor([-7.4470e-32,  4.3143e-41, -4.7637e-13,  4.3142e-41, -7.3144e-32,
         4.3143e-41,  1.0462e+06,  4.3143e-41, -4.7637e-13,  4.3142e-41])

In [36]:
print(i.dtype)
i = i.to(dtype = torch.float16)

torch.int64


In [37]:
print(i.dtype)

torch.float16


# Mathematical operation on tensors

In [1]:
import torch
x = torch.randint(1,10, (2,2))
print(x)
y = torch.randint(1,10, (2,2))
print(y)
scalar = 5

tensor([[2, 9],
        [6, 2]])
tensor([[3, 6],
        [4, 7]])


In [3]:
# Some scalar operation
print(x + 2) # scalar operation is performed on all the values
print(x - 2)
print(x / 2)

tensor([[ 4, 11],
        [ 8,  4]])
tensor([[0, 7],
        [4, 0]])
tensor([[1.0000, 4.5000],
        [3.0000, 1.0000]])


In [4]:
# element wise operation between two vectors of same shape
print(x + y) # all thing happen element wise
print(x - y)
print(x * y)
print(x / y)

tensor([[ 5, 15],
        [10,  9]])
tensor([[-1,  3],
        [ 2, -5]])
tensor([[ 6, 54],
        [24, 14]])
tensor([[0.6667, 1.5000],
        [1.5000, 0.2857]])


In [5]:
# element wise operation on a single vector
print(torch.abs(torch.tensor([[-1,-2] , [3,4]])))
print(torch.neg(torch.tensor([[-1,-2] , [3,4]])))

tensor([[1, 2],
        [3, 4]])
tensor([[ 1,  2],
        [-3, -4]])


In [8]:
print(torch.round(torch.tensor([[-1.43,-2.34] , [3.342,4.242]])))
print(torch.ceil(torch.tensor([[-1.43,-2.34] , [3.342,4.242]])))
print(torch.floor(torch.tensor([[-1.43,-2.34] , [3.342,4.242]])))



tensor([[-1., -2.],
        [ 3.,  4.]])
tensor([[-1., -2.],
        [ 4.,  5.]])
tensor([[-2., -3.],
        [ 3.,  4.]])


In [11]:
print(torch.clamp(torch.tensor([[-1.43,-2.34] , [3.342,4.242]]) , min = -2 , max = 4)) # to reduce to a range

tensor([[-1.4300, -2.0000],
        [ 3.3420,  4.0000]])


In [12]:
# Reduction operations : reducing down the entire vector in just a single number
a = torch.randint(low = 0 , high = 10 , size = (3,3))
print(a)

tensor([[9, 9, 9],
        [4, 9, 8],
        [7, 4, 0]])


In [27]:
torch.sum(a)

tensor(59)

In [28]:
torch.sum(a, axis = 0) # col wise sum

tensor([20, 22, 17])

In [29]:
torch.sum(a , axis = 1) # row wise sum

tensor([27, 21, 11])

In [30]:
torch.mean(a, dtype = torch.float64)

tensor(6.5556, dtype=torch.float64)

In [31]:
torch.mean(a , dtype = torch.float64, axis = 1)

tensor([9.0000, 7.0000, 3.6667], dtype=torch.float64)

In [32]:
torch.median(a)

tensor(8)

In [33]:
torch.max(a)

tensor(9)

In [34]:
torch.max(a, dim = 1)

torch.return_types.max(
values=tensor([9, 9, 7]),
indices=tensor([0, 1, 0]))

In [35]:
torch.max(a, axis = 1 )

torch.return_types.max(
values=tensor([9, 9, 7]),
indices=tensor([0, 1, 0]))

In [36]:
torch.argmax(a , axis = 1)

tensor([0, 1, 0])

In [37]:
torch.prod(a)

tensor(0)

In [42]:
torch.std(a.to(dtype = torch.float64), dim = 0)

tensor([2.5166, 2.8868, 4.9329], dtype=torch.float64)

In [44]:
torch.var(a.to(dtype = torch.float64), dim = 0)

tensor([ 6.3333,  8.3333, 24.3333], dtype=torch.float64)

In [45]:
# Some matrix operation :
a = torch.randint(low = 0 , high = 10 , size = (3,2))
b = torch.randint(low = 0 , high = 10 , size = (2,3))

print(a)
print(b)


tensor([[3, 5],
        [8, 6],
        [9, 3]])
tensor([[0, 4, 9],
        [8, 4, 9]])


In [52]:
sq_vec = torch.matmul(a,b)

In [53]:
vec1 = torch.tensor([1,2,3])
vec2 = torch.tensor([4,5,6])
print(torch.dot(vec1, vec2))

tensor(32)


In [54]:
torch.transpose(a, 0 , 1) # I want to swap 0 with 1

tensor([[3, 8, 9],
        [5, 6, 3]])

In [56]:
torch.det(sq_vec.to(dtype = torch.float64))

tensor(3.8369e-12, dtype=torch.float64)

In [59]:
torch.inverse(sq_vec.to(dtype = torch.float64))

tensor([[-1.7663e-17,  5.0000e-02, -5.8333e-02],
        [-5.6295e+14,  6.7554e+14, -4.1283e+14],
        [ 2.5020e+14, -3.0024e+14,  1.8348e+14]], dtype=torch.float64)

In [60]:
# Comparision operation
vec1 > vec2

tensor([False, False, False])

# Some special mathematical functions

In [6]:
import torch
torch.manual_seed(42)
a = torch.randint(1, 10 , (5, ))
print(a)

tensor([7, 6, 8, 5, 1])


In [7]:
torch.log(a)

tensor([1.9459, 1.7918, 2.0794, 1.6094, 0.0000])

In [8]:
torch.exp(a)

tensor([1.0966e+03, 4.0343e+02, 2.9810e+03, 1.4841e+02, 2.7183e+00])

In [9]:
torch.sqrt(a)

tensor([2.6458, 2.4495, 2.8284, 2.2361, 1.0000])

In [10]:
torch.sin(a)

tensor([ 0.6570, -0.2794,  0.9894, -0.9589,  0.8415])

In [11]:
torch.sigmoid(a)

tensor([0.9991, 0.9975, 0.9997, 0.9933, 0.7311])

In [12]:
1 / (1 + torch.exp(-a))

tensor([0.9991, 0.9975, 0.9997, 0.9933, 0.7311])

In [14]:
torch.softmax(a.to(dtype=torch.float64), dim = 0)

tensor([2.3674e-01, 8.7093e-02, 6.4354e-01, 3.2040e-02, 5.8683e-04],
       dtype=torch.float64)

In [15]:
torch.exp(a) / torch.sum(torch.exp(a))

tensor([2.3674e-01, 8.7093e-02, 6.4354e-01, 3.2040e-02, 5.8683e-04])

In [16]:
torch.relu(a)

tensor([7, 6, 8, 5, 1])

# Some other facts

In [1]:
import torch
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)
print(m+ n)
print(m) # no inplace changes

tensor([[0.0707, 0.0927, 0.9830],
        [0.4714, 0.7548, 0.4601]])
tensor([[0.9152, 0.8146, 0.1306],
        [0.2263, 0.7066, 0.7340]])
tensor([[0.9859, 0.9073, 1.1136],
        [0.6977, 1.4614, 1.1942]])
tensor([[0.0707, 0.0927, 0.9830],
        [0.4714, 0.7548, 0.4601]])


In [2]:
print(m.add_(n)) # inplace changes
print(m)

tensor([[0.9859, 0.9073, 1.1136],
        [0.6977, 1.4614, 1.1942]])
tensor([[0.9859, 0.9073, 1.1136],
        [0.6977, 1.4614, 1.1942]])


In [4]:
m.exp_()

tensor([[2.6803, 2.4777, 3.0452],
        [2.0091, 4.3121, 3.3009]])

In [5]:
m

tensor([[2.6803, 2.4777, 3.0452],
        [2.0091, 4.3121, 3.3009]])

In [6]:
# copying a tensor
a = torch.tensor([1,2,3])
b = a

In [8]:
a[2] = 10
print(b) # changed

tensor([ 1,  2, 10])


In [9]:
print(id(a) , id(b))

136872154099488 136872154099488


In [10]:
b = a.clone()
print(id(a) , id(b))

136872154099488 136872165548304


# How to use GPU

In [1]:
import torch
print(torch.cuda.is_available())

True


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [3]:
a = torch.rand(2,3,dtype = torch.float64, device = device)
print(a)

tensor([[0.8596, 0.0936, 0.7492],
        [0.0853, 0.1254, 0.2742]], device='cuda:0', dtype=torch.float64)


In [4]:
b = torch.rand(2,3,dtype = torch.float64, device = 'cpu')
print(b)

tensor([[0.4769, 0.4008, 0.1311],
        [0.1607, 0.5064, 0.8150]], dtype=torch.float64)


In [5]:
b.to(device = device)

tensor([[0.4769, 0.4008, 0.1311],
        [0.1607, 0.5064, 0.8150]], device='cuda:0', dtype=torch.float64)

In [6]:
print(b) # have to store the new tensor

tensor([[0.4769, 0.4008, 0.1311],
        [0.1607, 0.5064, 0.8150]], dtype=torch.float64)


# Reshaping of tensors

In [1]:
import torch

In [2]:
a = torch.ones(4,4)
print(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [4]:
a.reshape(2,2,2,2)


tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [5]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# permute operation to swap dimensions
b = torch.rand(2,3,4)
print(b)

tensor([[[0.4798, 0.2358, 0.6270, 0.9137],
         [0.3045, 0.3165, 0.6578, 0.2485],
         [0.7261, 0.4065, 0.0566, 0.5746]],

        [[0.6105, 0.5306, 0.0647, 0.9182],
         [0.2844, 0.0630, 0.6918, 0.8251],
         [0.7369, 0.3440, 0.0548, 0.0118]]])


In [7]:
b.permute(2,1,0)

tensor([[[0.4798, 0.6105],
         [0.3045, 0.2844],
         [0.7261, 0.7369]],

        [[0.2358, 0.5306],
         [0.3165, 0.0630],
         [0.4065, 0.3440]],

        [[0.6270, 0.0647],
         [0.6578, 0.6918],
         [0.0566, 0.0548]],

        [[0.9137, 0.9182],
         [0.2485, 0.8251],
         [0.5746, 0.0118]]])

In [8]:
# unsqueeze : add a dimension : can help in creating batches of data
c = torch.rand(224,224,3)
c.unsqueeze(0).shape

torch.Size([1, 224, 224, 3])

In [9]:
c.unsqueeze(1).shape

torch.Size([224, 1, 224, 3])

In [12]:
d = torch.rand(1,3,4)
print(d)

tensor([[[0.5459, 0.3410, 0.3377, 0.8707],
         [0.7641, 0.0858, 0.7703, 0.9384],
         [0.9837, 0.5693, 0.9332, 0.9478]]])


In [13]:
d.squeeze(0).shape

torch.Size([3, 4])

# Numpy and PyTorch Conversions

In [17]:
import torch
import numpy as np

In [18]:
a = torch.tensor([1,2,3])
print(a)
b = a.numpy()

tensor([1, 2, 3])


In [20]:
print(type(a), type(b))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [21]:
c = torch.from_numpy(b)

In [22]:
print(c, type(c), type(b))

tensor([1, 2, 3]) <class 'torch.Tensor'> <class 'numpy.ndarray'>
