In [1]:
import torch

# Autograd

Autograd is a very important module of PyTorch that can be used for differentiation purposes. It is very helpful for any kind of backpropagation.

When we put requires_gradient True, autograd tracks what all operation were done over that particular element

In [3]:
# then we calculate dL / db or dL/ dw

In [14]:
# y = x ** 2

x = torch.tensor([3], requires_grad = True, dtype = torch.float64)
y = x ** 2

In [15]:
print(x)

tensor([3.], dtype=torch.float64, requires_grad=True)


In [16]:
print(y)

tensor([9.], dtype=torch.float64, grad_fn=<PowBackward0>)


In [17]:
#y.grad # gradient only can be computed on the leafs nodes

In [18]:
y.backward()

In [19]:
x.grad # y can be only value

tensor([6.], dtype=torch.float64)

In [2]:
x = torch.tensor([3], requires_grad = True, dtype = torch.float64)
y = x ** 2
z = torch.sin(y)
print(x)
print(y)
print(z)

tensor([3.], dtype=torch.float64, requires_grad=True)
tensor([9.], dtype=torch.float64, grad_fn=<PowBackward0>)
tensor([0.4121], dtype=torch.float64, grad_fn=<SinBackward0>)


In [3]:
z.backward()

In [4]:
x.grad

tensor([-5.4668], dtype=torch.float64)

In [5]:
# sample neural network with one node CGPA vs placement
x = torch.tensor(6.7) # cgpa
y_target = torch.tensor(0.0) # unplaces

w = torch.tensor(1.0,  requires_grad = True, dtype = torch.float64)
b = torch.tensor(0.0,  requires_grad = True, dtype = torch.float64)

z = w*x + b
y_pred = torch.sigmoid(z)

loss =  - (y_target * torch.log(y_pred) + (1-y_target) * torch.log(1-y_pred))

In [7]:
x

tensor(6.7000)

In [8]:
w

tensor(1., dtype=torch.float64, requires_grad=True)

In [10]:
b

tensor(0., dtype=torch.float64, requires_grad=True)

In [11]:
z

tensor(6.7000, dtype=torch.float64, grad_fn=<AddBackward0>)

In [12]:
y_pred

tensor(0.9988, dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [13]:
loss

tensor(6.7012, dtype=torch.float64, grad_fn=<NegBackward0>)

In [14]:
loss.backward()

In [15]:
w.grad

tensor(6.6918, dtype=torch.float64)

In [16]:
b.grad

tensor(0.9988, dtype=torch.float64)

In [33]:
# vector input
a = torch.tensor([1,2,3], requires_grad = True, dtype = torch.float64)
b = (a**2).mean()

In [34]:
print(a)

tensor([1., 2., 3.], dtype=torch.float64, requires_grad=True)


In [35]:
print(b)

tensor(4.6667, dtype=torch.float64, grad_fn=<MeanBackward0>)


In [36]:
b.backward() # final value should be a single value

In [37]:
a.grad

tensor([0.6667, 1.3333, 2.0000], dtype=torch.float64)

In [ ]:
# clearing gradient : always clear before computing gradientes
b.grad.zero_() # inplace clearing

In [ ]:
# how to disable gradient tracking : like after training is done
#1. x.requires_grad_(False)
#2. with torch.no_grad() :
#     do some computation here , it wont be tracked
#3. z = x.detach() z is same as x but detached